--- #YAML:1.0
name:               POD2-ES
version:            5.12.3.01_3
abstract:           Documentación de Perl en español
author:
    - Equipo de Perl en Español
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POD2::Base:    0.043
    Pod::Perldoc:  3.15
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
